### ISSUE TITLE
Errors when use i18next with app folder and without locale in url

### ISSUE THREAD

**Issue by huybv98** [i18next/next-app-dir-i18next-no-locale-path-example#1]
This example , I have a errors "Unhandled Runtime Error
SyntaxError: "undefined" is not valid JSON" when click 'to client page" .
Thank you for your help :)

**Comment by adrai** [comment]
I'm not able to reproduce your exact issue, but I just updated the dependencies and also adapted the middleware: https://github.com/i18next/next-13-app-dir-i18next-no-locale-path-example/commit/94e993c1319d6898c00d1c5a274b44bf1f45382e

**Comment by huybv98** [comment]
I tried again and no problem.
Thank you for your help
