### ISSUE TITLE
Error when using client page and language other than "en"

### ISSUE THREAD

**Issue by vqhdev** [i18next/next-app-dir-i18next-no-locale-path-example#3]
## 🐛 Bug Report

I encountered these errors when using the 'client page' and the language is not 'fallbackLng', please see the attached image for error details.

![image](https://github.com/i18next/next-app-dir-i18next-no-locale-path-example/assets/133771786/b4f0e91e-e4f6-4c6b-938a-f215e77b9449)
![image](https://github.com/i18next/next-app-dir-i18next-no-locale-path-example/assets/133771786/32cffa0e-71fa-44e9-b380-f95a1efb6863)
![image](https://github.com/i18next/next-app-dir-i18next-no-locale-path-example/assets/133771786/1692fa21-bc66-4b57-b339-bfc82314777a)

## Your Environment

- *runtime version*: i.e. node v20.11.1
- *i18next version*: 23.5.1
- *os*: Windows

**Comment by adrai** [comment]
Yes, unfortunately that warning is because that client page is prerendered on serverside, and there we don't know what is the current language, because we can't access server side header invormation in a client component...

**Comment by jpainam** [comment]
The PR #2  seems to solves the problem?

**Comment by adrai** [comment]
You can do whatever you want... this is just an example repo

**Comment by adrai** [comment]
pr merged
